# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东每日签到

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京东签到'
        env: 
            COOKIE: ${{secrets.JD_COOKIE}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}  
            REMOTE_URL: https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
            CUSTOM_REPLACE : '[
                              {key : "!$nobyda.isNode", value :"$nobyda.isNode"},
                              {key : /(var Key = )''.*?''/, value : `$1''${(Secrets.COOKIE.split(SPLITSTR)[index])}''`},
                              {key : /if \(isNode\) (console.log\(.+?\))/, value : "if (isNode) {\nlet remotenotify = require(''./sendNotify'');\n remotenotify.sendNotify(`${title}\\n${subtitle}\\n${message}`,'''')\n}"}
                              ]'
            MULT_CUSTOM_REPLACE: '[[{key : /var Name.+/, value : "var Name = ''【签到帐号】:  YTX-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  SR-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  LJ-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  ZGX-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  WJY-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  LJ2-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  RQ-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  WRX-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  GC-'' + DName +''\\n''"}],
                                   [{key : /var Name.+/, value : "var Name = ''【签到帐号】:  WSR-'' + DName +''\\n''"}]
                                  ]'

        run: |
          node 'scripts/remote/runRemoteScripts.js'
